name: Create new release on version bump

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  check-release:
    name: Create release if it makes sense
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Create Release
        if: steps.info.outputs.version
        id: create_release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.info.outputs.version }}
          name: ${{ steps.info.outputs.version }}
          body_path: body.md
